spring:
  application:
    name: demo-provider

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    id: my-registry
  protocol:
    port: 20882
    name: dubbo
    id: dubbo
  application:
    name: demo-provider
    id: demo-provider
  scan:
    basePackages: org.hongxi.whatsmars.dubbo.demo.provider.service
